-- MySQL Script generated by MySQL Workbench
-- Fri Apr 30 22:05:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbTribos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbTribos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbTribos` DEFAULT CHARACTER SET utf8 ;
USE `dbTribos` ;

-- -----------------------------------------------------
-- Table `dbTribos`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTribos`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nmUsuario` VARCHAR(45) NOT NULL,
  `emailUsuario` VARCHAR(45) NULL,
  `senhaUsuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `emailUsuario_UNIQUE` (`emailUsuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbTribos`.`Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTribos`.`Grupo` (
  `idGrupo` INT NOT NULL AUTO_INCREMENT,
  `nmGrupo` VARCHAR(45) NOT NULL,
  `descGrupo` VARCHAR(200) NULL,
  `idUsuarioCriou` INT NOT NULL,
  PRIMARY KEY (`idGrupo`),
  UNIQUE INDEX `nmGrupo_UNIQUE` (`nmGrupo` ASC),
  INDEX `fk_Grupo_Usuario1_idx` (`idUsuarioCriou` ASC),
  CONSTRAINT `fk_Grupo_Usuario1`
    FOREIGN KEY (`idUsuarioCriou`)
    REFERENCES `dbTribos`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbTribos`.`GruposUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTribos`.`GruposUsuario` (
  `idGrupoUsuario` INT NOT NULL AUTO_INCREMENT,
  `idGrupo` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  INDEX `fk_Usuario_has_Grupo_Grupo1_idx` (`idGrupo` ASC),
  INDEX `fk_Usuario_has_Grupo_Usuario_idx` (`idUsuario` ASC),
  PRIMARY KEY (`idGrupoUsuario`),
  CONSTRAINT `fk_Usuario_has_Grupo_Usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `dbTribos`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Grupo_Grupo1`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `dbTribos`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbTribos`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTribos`.`Evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `dtCriado` TIMESTAMP(6) NULL,
  `dtEvento` DATE NOT NULL,
  `hrEvento` TIME NULL,
  `nmEvento` VARCHAR(45) NOT NULL,
  `descEvento` VARCHAR(200) NULL,
  `qtPartsEvento` INT NOT NULL,
  `flEventoPrivado` ENUM('s', 'n') NULL,
  `localEvento` VARCHAR(200) NOT NULL,
  `numLocalEvento` INT NOT NULL,
  `idGrupoCriou` INT NOT NULL,
  PRIMARY KEY (`idEvento`),
  INDEX `fk_Evento_Grupo1_idx` (`idGrupoCriou` ASC),
  CONSTRAINT `fk_Evento_Grupo1`
    FOREIGN KEY (`idGrupoCriou`)
    REFERENCES `dbTribos`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbTribos`.`AvaliacaoEvento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTribos`.`AvaliacaoEvento` (
  `idAvaliacaoEvento` INT NOT NULL AUTO_INCREMENT,
  `qtPtsAvaliacao` INT NOT NULL,
  `dtCriado` TIMESTAMP(6) NULL,
  `idUsurioAvaliou` INT NOT NULL,
  `idEvento` INT NOT NULL,
  PRIMARY KEY (`idAvaliacaoEvento`),
  INDEX `fk_AvaliacaoEvento_Usuario1_idx` (`idUsurioAvaliou` ASC),
  INDEX `fk_AvaliacaoEvento_Evento1_idx` (`idEvento` ASC),
  CONSTRAINT `fk_AvaliacaoEvento_Usuario1`
    FOREIGN KEY (`idUsurioAvaliou`)
    REFERENCES `dbTribos`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AvaliacaoEvento_Evento1`
    FOREIGN KEY (`idEvento`)
    REFERENCES `dbTribos`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbTribos`.`EventosUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTribos`.`EventosUsuario` (
  `idEventoUsuario` INT NOT NULL AUTO_INCREMENT,
  `idEvento` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  INDEX `fk_Evento_has_Usuario_Usuario1_idx` (`idUsuario` ASC),
  INDEX `fk_Evento_has_Usuario_Evento1_idx` (`idEvento` ASC),
  PRIMARY KEY (`idEventoUsuario`),
  CONSTRAINT `fk_Evento_has_Usuario_Evento1`
    FOREIGN KEY (`idEvento`)
    REFERENCES `dbTribos`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_has_Usuario_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `dbTribos`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
