-- MySQL Script generated by MySQL Workbench
-- Sat Apr 17 22:18:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbTribos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbTribos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbTribos` DEFAULT CHARACTER SET utf8 ;
USE `dbTribos` ;

-- -----------------------------------------------------
-- Table `dbTribos`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTribos`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nmUsuario` VARCHAR(45) NOT NULL,
  `emailUsuario` VARCHAR(45) NULL,
  `senhaUsuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `emailUsuario_UNIQUE` (`emailUsuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbTribos`.`Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTribos`.`Grupo` (
  `idGrupo` INT NOT NULL AUTO_INCREMENT,
  `nmGrupo` VARCHAR(45) NOT NULL,
  `descGrupo` VARCHAR(200) NULL,
  PRIMARY KEY (`idGrupo`),
  UNIQUE INDEX `nmGrupo_UNIQUE` (`nmGrupo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbTribos`.`GrupoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTribos`.`GrupoUsuario` (
  `idGrupoUsuario` INT NOT NULL,
  `idGrupo` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  INDEX `fk_Usuario_has_Grupo_Grupo1_idx` (`idGrupo` ASC),
  INDEX `fk_Usuario_has_Grupo_Usuario_idx` (`idUsuario` ASC),
  PRIMARY KEY (`idGrupoUsuario`),
  CONSTRAINT `fk_Usuario_has_Grupo_Usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `dbTribos`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Grupo_Grupo1`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `dbTribos`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbTribos`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTribos`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nmCategoria` VARCHAR(45) NOT NULL,
  `descCategoria` VARCHAR(200) NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `nmCategoria_UNIQUE` (`nmCategoria` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbTribos`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTribos`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nmEstado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbTribos`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTribos`.`Cidade` (
  `idCidade` INT NOT NULL AUTO_INCREMENT,
  `nmCidade` VARCHAR(45) NOT NULL,
  `idEstado` INT NOT NULL,
  PRIMARY KEY (`idCidade`),
  INDEX `fk_Cidade_Estado1_idx` (`idEstado` ASC),
  CONSTRAINT `fk_Cidade_Estado1`
    FOREIGN KEY (`idEstado`)
    REFERENCES `dbTribos`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbTribos`.`Bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTribos`.`Bairro` (
  `idBairro` INT NOT NULL AUTO_INCREMENT,
  `nmBairro` VARCHAR(45) NOT NULL,
  `idCidade` INT NOT NULL,
  PRIMARY KEY (`idBairro`),
  INDEX `fk_Bairro_Cidade1_idx` (`idCidade` ASC),
  CONSTRAINT `fk_Bairro_Cidade1`
    FOREIGN KEY (`idCidade`)
    REFERENCES `dbTribos`.`Cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbTribos`.`Logradouro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTribos`.`Logradouro` (
  `idLogradouro` INT NOT NULL AUTO_INCREMENT,
  `nmLogradouro` VARCHAR(45) NOT NULL,
  `idBairro` INT NOT NULL,
  `cepLogradouro` VARCHAR(45) NULL,
  PRIMARY KEY (`idLogradouro`),
  INDEX `fk_Logradouro_Bairro1_idx` (`idBairro` ASC),
  CONSTRAINT `fk_Logradouro_Bairro1`
    FOREIGN KEY (`idBairro`)
    REFERENCES `dbTribos`.`Bairro` (`idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbTribos`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTribos`.`Evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `dtCriado` TIMESTAMP(6) NULL,
  `dtEvento` TIMESTAMP(6) NULL,
  `nmEvento` VARCHAR(45) NOT NULL,
  `descEvento` VARCHAR(200) NULL,
  `qtParts` INT NOT NULL,
  `flPrivado` ENUM('s', 'n') NULL,
  `idLocalEvento` INT NOT NULL,
  `numLocalEvento` INT NOT NULL,
  `idUsuarioCriou` INT NOT NULL,
  PRIMARY KEY (`idEvento`),
  INDEX `fk_Evento_Logradouro1_idx` (`idLocalEvento` ASC),
  INDEX `fk_Evento_Usuario1_idx` (`idUsuarioCriou` ASC),
  CONSTRAINT `fk_Evento_Logradouro1`
    FOREIGN KEY (`idLocalEvento`)
    REFERENCES `dbTribos`.`Logradouro` (`idLogradouro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_Usuario1`
    FOREIGN KEY (`idUsuarioCriou`)
    REFERENCES `dbTribos`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbTribos`.`CategoriaEvento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTribos`.`CategoriaEvento` (
  `idCategoriaEvento` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  `idEvento` INT NOT NULL,
  INDEX `fk_Categoria_has_Evento_Evento1_idx` (`idEvento` ASC),
  INDEX `fk_Categoria_has_Evento_Categoria_idx` (`idCategoria` ASC),
  PRIMARY KEY (`idCategoriaEvento`),
  CONSTRAINT `fk_Categoria_has_Evento_Categoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `dbTribos`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categoria_has_Evento_Evento1`
    FOREIGN KEY (`idEvento`)
    REFERENCES `dbTribos`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `dbTribos`.`SugestaoEvento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTribos`.`SugestaoEvento` (
  `idSugestaoEvento` INT NOT NULL AUTO_INCREMENT,
  `descSugestao` VARCHAR(200) NULL,
  `dtCriado` TIMESTAMP(6) NULL,
  `idUsuarioSugeriu` INT NOT NULL,
  `idUsuarioCriador` INT NOT NULL,
  PRIMARY KEY (`idSugestaoEvento`, `idUsuarioSugeriu`, `idUsuarioCriador`),
  INDEX `fk_SugestaoEvento_Usuario1_idx` (`idUsuarioSugeriu` ASC),
  INDEX `fk_SugestaoEvento_Usuario2_idx` (`idUsuarioCriador` ASC),
  CONSTRAINT `fk_SugestaoEvento_Usuario1`
    FOREIGN KEY (`idUsuarioSugeriu`)
    REFERENCES `dbTribos`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SugestaoEvento_Usuario2`
    FOREIGN KEY (`idUsuarioCriador`)
    REFERENCES `dbTribos`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbTribos`.`AvaliacaoEvento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTribos`.`AvaliacaoEvento` (
  `idAvaliacaoEvento` INT NOT NULL AUTO_INCREMENT,
  `qtPtsAvaliacao` INT NOT NULL,
  `dtCriado` TIMESTAMP(6) NULL,
  `idUsurioAvaliou` INT NOT NULL,
  `idEvento` INT NOT NULL,
  PRIMARY KEY (`idAvaliacaoEvento`),
  INDEX `fk_AvaliacaoEvento_Usuario1_idx` (`idUsurioAvaliou` ASC),
  INDEX `fk_AvaliacaoEvento_Evento1_idx` (`idEvento` ASC),
  CONSTRAINT `fk_AvaliacaoEvento_Usuario1`
    FOREIGN KEY (`idUsurioAvaliou`)
    REFERENCES `dbTribos`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AvaliacaoEvento_Evento1`
    FOREIGN KEY (`idEvento`)
    REFERENCES `dbTribos`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
